name: Profile README Manual

on:
  workflow_dispatch:

jobs:
  keep-readme-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Keep profile README manual
        run: echo "README.md is maintained manually."
